import { ChatListResponse } from "../../../entities/chat/model/types";

export const mockChats: ChatListResponse = {
  count: 42,
  next: null,
  previous: null,
  results: [
    {
      id: 1,
      chat: {
        uid: "1",
        username: "vlad_lyashev",
        nickname: "Влад",
        first_name: "Влад",
        last_name: "",
        avatar: null,
        avatar_url: "./auth/success.svg",
        avatar_webp: null,
        avatar_webp_url: null,
        is_blocked: false,
        is_online: true,
        was_online_at: 0,
        is_in_contacts: true,
      },
      is_favorite: false,
      notifications: true,
      new_message_count: 0,
      new_file_count: 0,
      name: "",
      chat_type: "chat",
      chat_key: "c_1",
      last_activity_at: Date.now() / 1000 - 60,
      last_message: {
        id: 101,
        uid: "m1",
        from_user: "1",
        content: "Привет, Владик!",
        files_summary: null,
        has_replied_message: false,
        has_forwarded_message: true,
        new: false,
        created_at: Date.now() / 1000 - 60,
        updated_at: Date.now() / 1000 - 60,
      },
    },
    {
      id: 2,
      chat: {
        uid: "2",
        username: "sergey_evt",
        nickname: null,
        first_name: "Сергей",
        last_name: "Евтушенко",
        avatar: null,
        avatar_url: null,
        avatar_webp: null,
        avatar_webp_url: null,
        is_online: false,
        was_online_at: Date.now() / 1000 - 3600,
        is_blocked: false,
        is_in_contacts: true,
      },
      is_favorite: false,
      notifications: true,
      new_message_count: 2,
      new_file_count: 0,
      name: "",
      chat_type: "chat",
      chat_key: "c_2",
      last_activity_at: Date.now() / 1000 - 120,
      last_message: {
        id: 102,
        uid: "m2",
        from_user: "2",
        content: "Привет. Я оставил две стерманки и два шуруповёрта. Один в кейсе, а др...",
        new: false,
        has_forwarded_message: true,
        created_at: Date.now() / 1000 - 120,
        updated_at: Date.now() / 1000 - 120,
      },
    },
    {
      id: 3,
      chat: {
        uid: "5",
        username: "nastya_bort",
        nickname: "Анастасия Бортникова",
        first_name: "Анастасия",
        last_name: "Бортникова",
        avatar_webp_url: "",
        is_online: true,
        was_online_at: Date.now() / 1000 - 300,
        is_blocked: false,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: true,
      new_message_count: 2,
      new_file_count: 0,
      name: "",
      chat_type: "chat",
      chat_key: "c_5",
      last_activity_at: Date.now() / 1000 - 300,
      last_message: {
        id: 105,
        uid: "m5",
        from_user: "5",
        content: "У меня кошка родила",
        new: true,
        created_at: Date.now() / 1000 - 300,
        updated_at: Date.now() / 1000 - 300,
      },
    },
    {
      id: 4,
      chat: {
        uid: "7",
        username: "alex_mitro",
        nickname: null,
        first_name: "Алексей",
        last_name: "Митрофанов",
        was_online_at: Date.now() / 1000 - 86400 * 2,
        avatar: null,
        avatar_webp_url: null,
        is_online: false,
        is_blocked: false,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: false,
      new_message_count: 56,
      new_file_count: 3,
      name: "",
      chat_type: "chat",
      chat_key: "c_7",
      last_activity_at: Date.now() / 1000 - 86400 * 2,
      last_message: {
        id: 107,
        uid: "m7",
        from_user: "me",
        content: "Сходили в парк прогуляться. Смотри какая красота!",
        files_summary: { types: ["jpg", "mp4"], count: 2 },
        // has_forwarded_message: true,
        new: true,
        created_at: Date.now() / 1000 - 86400 * 2,
        updated_at: Date.now() / 1000 - 86400 * 2,
      },
    },
    {
      id: 5,
      chat: {
        uid: "10",
        was_online_at: Date.now() / 1000 - 86400 * 5,
        username: "vanessa_reich",
        nickname: "Ванесса Рейхарт",
        first_name: "Ванесса",
        last_name: "Рейхарт",
        avatar_webp_url: "",
        is_online: false,
        is_blocked: false,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: true,
      new_message_count: 0,
      new_file_count: 0,
      name: "",
      chat_type: "chat",
      chat_key: "c_10",
      last_activity_at: Date.now() / 1000 - 86400 * 5,
      last_message: {
        id: 110,
        uid: "m10",
        from_user: "10",
        content: "Сделали прекрасный стейк вчера. Вау! Обязательно угощу вас!",
        new: false,
        created_at: Date.now() / 1000 - 86400 * 5,
        updated_at: Date.now() / 1000 - 86400 * 5,
      },
    },
    {
      id: 6,
      chat: {
        uid: "11",
        username: "kostya_pered",
        first_name: "Константин",
        last_name: "Передв...",
        nickname: null,
        avatar_webp_url: "",
        was_online_at: Date.now() / 1000 - 1800,
        is_online: true,
        is_blocked: false,
        is_in_contacts: false,
      },
      is_favorite: false,
      notifications: true,
      new_message_count: 2,
      new_file_count: 1,
      name: "",
      chat_type: "chat",
      chat_key: "c_11",
      last_activity_at: Date.now() / 1000 - 1800,
      last_message: {
        id: 111,
        uid: "m11",
        from_user: "11",
        content: "doc90498820200806132640.pdf",
        files_summary: { types: ["pdf"], count: 1 },
        new: true,
        created_at: Date.now() / 1000 - 1800,
        updated_at: Date.now() / 1000 - 1800,
      },
    },
    {
      id: 7,
      chat: {
        uid: "12",
        username: "inna_georg",
        first_name: "Инна",
        last_name: "Георгиевна",
        nickname: null,
        avatar_webp_url: "",
        was_online_at: Date.now() / 1000 - 3600 * 4,
        is_online: true,
        is_blocked: false,
        is_in_contacts: true,
      },
      is_favorite: false,
      notifications: true,
      new_message_count: 0,
      new_file_count: 0,
      name: "Инна Георгиевна",
      chat_type: "chat",
      chat_key: "c_12",
      last_activity_at: Date.now() / 1000 - 3600 * 4,
      last_message: {
        id: 112,
        uid: "m12",
        from_user: "me",
        content: "",
        files_summary: { types: ["jpg"], count: 4 },
        new: false,
        created_at: Date.now() / 1000 - 3600 * 4,
        updated_at: Date.now() / 1000 - 3600 * 4,
      },
    },
    {
      id: 8,
      chat: {
        uid: "14",
        username: "inna",
        first_name: "Борис",
        last_name: "Клеменьтев",
        nickname: null,
        avatar_webp_url: "",
        was_online_at: Date.now() / 1000 - 3600 * 5,
        is_online: true,
        is_blocked: false,
        is_in_contacts: true,
      },
      is_favorite: false,
      notifications: true,
      new_message_count: 0,
      new_file_count: 0,
      name: "Борис Клеменьтев",
      chat_type: "chat",
      chat_key: "c_14",
      last_activity_at: Date.now() / 1000 - 3600 * 5,
      last_message: {
        id: 112,
        uid: "m12",
        from_user: "me",
        content: "",
        files_summary: { types: ["jpg", "mp4", "jpg"], count: 2 },
        new: false,
        created_at: Date.now() / 1000 - 3600 * 5,
        updated_at: Date.now() / 1000 - 3600 * 4,
      },
    },
  ],
};
