import "./globals.css";
import "./globals.css";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import { SITE_TITLE } from "@/shared/lib/constants/siteInfo";
import { WSProvider } from "@/shared/providers/wsProvider";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: `${SITE_TITLE}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${roboto.variable} font-sans antialiased`}>
        <WSProvider>{children}</WSProvider>
      </body>
    </html>
  );
}
