import "./globals.css";

import type { Metadata } from "next";
import { Noto_Color_Emoji, Roboto } from "next/font/google";
import localFont from "next/font/local";

import { SITE_TITLE } from "@/shared/lib/constants/siteInfo";
import { AuthGuard } from "@/shared/providers/authGuard";
import { IsMobileProvider } from "@/shared/providers/isMobileProvider";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: `${SITE_TITLE}`,
  description: "Generated by create next app",
};

const notoColorEmoji = Noto_Color_Emoji({
  variable: "--font-noto-color-emoji",
  weight: "400",
  subsets: ["emoji"],
});

export const appleColorEmoji = localFont({
  src: "./fonts/Emoji-subset.woff2",
  weight: "400",
  style: "normal",
  display: "swap",
  variable: "--font-apple-color-emoji",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${roboto.variable} ${notoColorEmoji.variable} ${appleColorEmoji.variable} font-sans antialiased`}
      >
        <IsMobileProvider>
          <AuthGuard>{children}</AuthGuard>
        </IsMobileProvider>
      </body>
    </html>
  );
}
