import type { Metadata } from "next";
import { Roboto, Noto_Color_Emoji } from "next/font/google";
import "./globals.css";
import { SITE_TITLE } from "@/shared/lib/constants/siteInfo";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: `${SITE_TITLE}`,
  description: "Generated by create next app",
};

const notoColorEmoji = Noto_Color_Emoji({
  variable: "--font-noto-color-emoji",
  weight: "400",
  subsets: ["emoji"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${roboto.variable} ${notoColorEmoji.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
