export const mockMessagesPage = {
  count: 12,
  next: "http://api.example.org/messages/?page=2",
  previous: null,
  results: [
    {
      id: 1,
      uid: "msg-1",
      from_user: {
        uid: "user-1",
        username: "bigboss",
        nickname: "Big Boss",
        first_name: "Ivan",
        last_name: "Petrov",
        patronymic: "",
        avatar_url: "/avatars/user-1.jpg",
        avatar_webp_url: "/avatars/user-1.webp",
      },
      to_user: {
        uid: "user-2",
        username: "alex",
        nickname: "Alex",
        first_name: "Alexey",
        last_name: "Smirnov",
        patronymic: "",
        avatar_url: "/avatars/user-2.jpg",
        avatar_webp_url: "/avatars/user-2.webp",
      },
      content: "Привет! Ты видел последний апдейт?",
      replied_messages: [],
      forwarded_messages: [],
      files_list: [],
      new: false,
      created_at: 1703875200, // 30 декабря 2023 10:00
      updated_at: 1703875200,
      chat_id: 100,
      chat_key: "chat-100",
      chat_type: "private",
      message_rtc: null,
    },

    {
      id: 2,
      uid: "msg-2",
      from_user: {
        uid: "user-2",
        username: "alex",
        nickname: "Alex",
        first_name: "Alexey",
        last_name: "Smirnov",
        patronymic: "",
        avatar_url: "/avatars/user-2.jpg",
        avatar_webp_url: "/avatars/user-2.webp",
      },
      to_user: {
        uid: "user-1",
        username: "bigboss",
        nickname: "Big Boss",
        first_name: "Ivan",
        last_name: "Petrov",
        patronymic: "",
        avatar_url: "/avatars/user-1.jpg",
        avatar_webp_url: "/avatars/user-1.webp",
      },
      content: "Да, выглядит круто 👌",
      replied_messages: [],
      forwarded_messages: [],
      files_list: [],
      new: false,
      created_at: 1703875500, // +5 минут
      updated_at: 1703875500,
      chat_id: 100,
      chat_key: "chat-100",
      chat_type: "private",
      message_rtc: null,
    },

    {
      id: 3,
      uid: "msg-3",
      from_user: {
        uid: "user-1",
        username: "bigboss",
        nickname: "Big Boss",
        first_name: "Ivan",
        last_name: "Petrov",
        patronymic: "",
        avatar_url: "/avatars/user-1.jpg",
        avatar_webp_url: "/avatars/user-1.webp",
      },
      to_user: {
        uid: "user-2",
        username: "alex",
        nickname: "Alex",
        first_name: "Alexey",
        last_name: "Smirnov",
        patronymic: "",
        avatar_url: "/avatars/user-2.jpg",
        avatar_webp_url: "/avatars/user-2.webp",
      },
      content: "Скидываю скрин",
      replied_messages: [],
      forwarded_messages: [],
      files_list: [
        {
          id: 10,
          uid: "file-10",
          file: "screenshot.png",
          file_url: "/files/screenshot.png",
          file_webp: "screenshot.webp",
          file_webp_url: "/files/screenshot.webp",
          file_type: "image",
          new: false,
          created_at: 1703875600,
          updated_at: 1703875600,
        },
      ],
      new: false,
      created_at: 1703875600,
      updated_at: 1703875600,
      chat_id: 100,
      chat_key: "chat-100",
      chat_type: "private",
      message_rtc: null,
    },

    {
      id: 4,
      uid: "msg-4",
      from_user: {
        uid: "user-2",
        username: "alex",
        nickname: "Alex",
        first_name: "Alexey",
        last_name: "Smirnov",
        patronymic: "",
        avatar_url: "/avatars/user-2.jpg",
        avatar_webp_url: "/avatars/user-2.webp",
      },
      to_user: {
        uid: "user-1",
        username: "bigboss",
        nickname: "Big Boss",
        first_name: "Ivan",
        last_name: "Petrov",
        patronymic: "",
        avatar_url: "/avatars/user-1.jpg",
        avatar_webp_url: "/avatars/user-1.webp",
      },
      content: "Вот это сообщение было раньше",
      replied_messages: [],
      forwarded_messages: [],
      files_list: [],
      new: true,
      created_at: 1703788800, // 29 декабря 2023
      updated_at: 1703788800,
      chat_id: 100,
      chat_key: "chat-100",
      chat_type: "private",
      message_rtc: null,
    },
  ],
};
